In [2]:
import pandas as pd
import json

In [3]:
path = "../data/weather_data.json"

In [13]:
with open(path, "r") as f:
    data = pd.json_normalize(json.load(f))
df= data

In [14]:
df.head()

,weather,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,...,main.sea_level,main.grnd_level,wind.speed,wind.deg,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset
0,"[{'id': 804, 'main': 'Clouds', 'description': ...",stations,10000,1789352370,-10800,3448439,São Paulo,200,-46.6361,-23.5475,...,1024,930,3.6,160,100,1,8394,BR,1789290336,1789333181

In [7]:
df.describe()

,visibility,dt,timezone,id,cod,coord.lon,coord.lat,main.temp,main.feels_like,main.temp_min,...,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,clouds.all,sys.type,sys.id,sys.sunrise,sys.sunset
count,1.0,1.000000e+00,1.0,1.0,1.0,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000e+00,1.000000e+00
mean,10000.0,1.789352e+09,-10800.0,3448439.0,200.0,-46.6361,-23.5475,14.62,14.64,14.14,...,96.0,1024.0,930.0,3.6,160.0,100.0,1.0,8394.0,1.789290e+09,1.789333e+09
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,10000.0,1.789352e+09,-10800.0,3448439.0,200.0,-46.6361,-23.5475,14.62,14.64,14.14,...,96.0,1024.0,930.0,3.6,160.0,100.0,1.0,8394.0,1.789290e+09,1.789333e+09
25%,10000.0,1.789352e+09,-10800.0,3448439.0,200.0,-46.6361,-23.5475,14.62,14.64,14.14,...,96.0,1024.0,930.0,3.6,160.0,100.0,1.0,8394.0,1.789290e+09,1.789333e+09
50%,10000.0,1.789352e+09,-10800.0,3448439.0,200.0,-46.6361,-23.5475,14.62,14.64,14.14,...,96.0,1024.0,930.0,3.6,160.0,100.0,1.0,8394.0,1.789290e+09,1.789333e+09
75%,10000.0,1.789352e+09,-10800.0,3448439.0,200.0,-46.6361,-23.5475,14.62,14.64,14.14,...,96.0,1024.0,930.0,3.6,160.0,100.0,1.0,8394.0,1.789290e+09,1.789333e+09
max,10000.0,1.789352e+09,-10800.0,3448439.0,200.0,-46.6361,-23.5475,14.62,14.64,14.14,...,96.0,1024.0,930.0,3.6,160.0,100.0,1.0,8394.0,1.789290e+09,1.789333e+09

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   weather          1 non-null      object
 1   base             1 non-null      object
 2   visibility       1 non-null      int64
 3   dt               1 non-null      int64
 4   timezone         1 non-null      int64
 5   id               1 non-null      int64
 6   name             1 non-null      object
 7   cod              1 non-null      int64
 8   coord.lon        1 non-null      float64
 9   coord.lat        1 non-null      float64
 10  main.temp        1 non-null      float64
 11  main.feels_like  1 non-null      float64
 12  main.temp_min    1 non-null      float64
 13  main.temp_max    1 non-null      float64
 14  main.pressure    1 non-null      int64
 15  main.humidity    1 non-null      int64
 16  main.sea_level   1 non-null      int64
 17  main.grnd_level  1 non-null      int64
 18  wind.speed       1 non-null      float64
 19  wind.deg         1 non-null      int64
 20  clouds.all       1 non-null      int64
 21  sys.type         1 non-null      int64
 22  sys.id           1 non-null      int64
 23  sys.country      1 non-null      object
 24  sys.sunrise      1 non-null      int64
 25  sys.sunset       1 non-null      int64
dtypes: float64(7), int64(15), object(4)
memory usage: 336.0+ bytes